@baseUrl= http://localhost:3001/api

@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDVjNzg1NzZhMGIzNTM5MDE3NzZlYTAiLCJuYW1lIjoibW9udHkiLCJpYXQiOjE2ODM3ODQ1ODAsImV4cCI6MTY4Mzc4ODE4MH0.HPBdMBJ1T0g3avry7sBXDAGmofriuRkWVwtxRsF4KkE

###

POST http://localhost:3001/api/user
content-type: application/json
Authorization: Bearer {{token}}

{
    "email":"monty@gmail.com"
    

}

###
POST {{baseUrl}}/auth/signup
content-type: application/json

{
    "name": "vs",
    "email":"vs@gmail.com",
    "password": "password@123",
    "number":1234567891
}


###
POST {{baseUrl}}/auth/verify
content-type: application/json

{
    "number":1234567893,
    "otp":"348011"
}

###
POST {{baseUrl}}/auth/login
content-type: application/json

{
    
    "email":"monty@gmail.com",
    "password": "password@123"

}


###
POST {{baseUrl}}/auth/logout
content-type: application/json
Authorization: Bearer {{token}}


//////////////////////tag requests //////////////////////////////////////////
###
POST {{baseUrl}}/tag 
content-type: application/json 
Authorization: Bearer {{token}}

{
"name":"Artificial Intelligence"
}

### 
GET {{baseUrl}}/tag 
content-type: application/json
Authorization: Bearer {{token}}

### 
GET {{baseUrl}}/tag/645a45ad29205a5ac0046864 
content-type: application/json 
Authorization: Bearer {{token}}